services:
  - type: web
    name: bookmark-backend
    env: node
    repo: https://github.com/fahimfaisaal/bookmark
    branch: deploy_backend
    rootDir: ./backend
    buildCommand: yarn; yarn build
    startCommand: yarn start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: ~16.15.0
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_NAME
        sync: true
        value: null
      - key: CLOUDINARY_KEY
        sync: true
        value: null
      - key: CLOUDINARY_SECRET
        sync: true
        value: null
      - key: DATABASE_URL_PRODUCTION
        fromDatabase:
          name: bookmark-backend-db
          property: connectionString
      - key: JWT_SECRET_PRODUCTION
        generateValue: true
      - key: ADMIN_JWT_SECRET_PRODUCTION
        generateValue: true
      - key: APP_KEYS_PRODUCTION
        generateValue: true
      - key: API_TOKEN_SALT_PRODUCTION
        generateValue: true
databases:
  - name: bookmark backend db
    databaseName: bookmarkdb
    plan: free
