services:
  - type: web
    name: bookmark-backend
    env: node
    plan: starter
    buildCommand: yarn; yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: ~16.15.0
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_NAME
        sync: true
      - key: CLOUDINARY_KEY
        sync: true
      - key: CLOUDINARY_SECRET
        sync: true
      - key: DATABASE_URL_PRODUCTION
        fromDatabase:
        sync: true
      - key: JWT_SECRET_PRODUCTION
        generateValue: true
      - key: ADMIN_JWT_SECRET_PRODUCTION
        generateValue: true
      - key: APP_KEYS_PRODUCTION
        generateValue: true
